### ISSUE TITLE
Latest Garm and Version 2 Maintenance

### ISSUE THREAD

**Issue by mlajkim** [AthenZ/garm#31]
# Background
The latest Garm in `v3.0.3` only supports the latest ones, and it might be hard for the Garm v2 user to move up without downtime.

## TODOs
```
- [ ] Apply vulnerability handle for v2
- [ ] Fix the regex problem for v2
- [ ] Apply the conversion method for v2
- [ ] Apply the latest vulnerability patch that was handled in v2 
```
